dlilis/dlili/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dlilis.video.urls'))
]

dlilis/video/urls.py
from django.urls import path
from . import views

app_name = 'video'  # 建议使用app_name
urlpatterns = [  # 注意使用的是 [] 非 {}
    path('', views.index, name='index'),
    path('detail/<int:video_id>', views.detail, name='detail'),

]

dlilis/video/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Category(models.Model):
    '''
    视频分类
    '''
    name = models.CharField(max_length=50, verbose_name=u'视频分类')
    number = models.IntegerField(default=0, verbose_name=u'分类数目')

    def __str__(self):  # 记得加上str,str中属性用self.xxx
        return self.name


class Tag(models.Model):
    '''
    视频标签
    '''
    name = models.CharField(max_length=10, verbose_name=u'视频标签')
    number = models.IntegerField(default=0, verbose_name=u'标签数量')

    def __str__(self):
        return self.name


class Video(models.Model):
    '''
    视频
    '''
    title = models.CharField(max_length=50, verbose_name=u'视频名称')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')
    modify_time = models.DateTimeField(auto_now=True, verbose_name=u'修改时间')
    message = models.TextField(verbose_name=u'相关信息', blank=True)
    image_url = models.CharField(max_length=200, verbose_name=u'封面地址', blank=True)
    score = models.FloatField(default=0.0, verbose_name=u'评分')
    intro = models.TextField(verbose_name=u'简介', blank=True)
    photo_url = models.TextField(verbose_name=u'剧照', blank=True)
    play_url = models.TextField(verbose_name=u'下载链接', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=u'分类')
    tag = models.ManyToManyField(Tag, verbose_name=u'标签')
    num = models.IntegerField(default=0, verbose_name=u'点击量')

    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.create_time >= timezone.now() - datetime.timedelta(days=7)


class Comment(models.Model):
    '''
    评论
    '''
    name = models.CharField(max_length=20, default=u'佚名', verbose_name=u'用户名')
    content = models.CharField(max_length=400)
    num = models.IntegerField(default=0, verbose_name=u'评论数')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'评论时间')
    blog = models.ForeignKey(Video, on_delete=models.CASCADE, verbose_name=u'视频')
    patent_comtents = models.ForeignKey('self', on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ':' + self.content


dlilis/video/views.py
from django.shortcuts import render, get_object_or_404
from .models import Video


# Create your views here.
def index(request):
    '''
    主页
    :param request:
    :return:
    '''
    last_video = []
    for video in Video.objects.all():
        if video.was_published_recently():
            last_video.append(video)
    context = {
        'last_video': last_video
    }
    return render(request, 'video/index.html', context)


def detail(request, video_id):
    '''
    详情页
    :param request:
    :return:
    '''
    video = get_object_or_404(Video, pk=video_id)
    return render(request, 'video/detail.html', {'video': video})



dlilis/video/templates/video/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{video.image_url}}
<p>{{video.message}}</p>
<p>播放列表:
{{video.play_url}}</p>
<p>{{video.intro}}</p>
</body>
</html>

dlilis/video/templates/video/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <!-- 响应式视口元标记 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-compatible" content="IE=edge,chrome=1">

    <title>享受美味的影视时光</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css" media="all">
    <!--字体图标-->

</head>
<body class="container-fluid">
   <header class="header container-fluid">
       <div class="container">
           <div class="header-area row">
           <div class="logo col-lg-3">
               <a href="{% url 'video:index' %}"><img src="../../static/images/logo.png"></a>
           </div>
           <div class="header-mid col-lg-8">
                   <div class="seach float-right">
                   <form action="#">
                       <select>
                           <option value="Movie">Movie</option>
                           <option vlaue="TVplay">TVplay</option>
                       </select>
                       <input type="search">
                       <button><i class="icon .glyphicon .glyphicon-search"></i></button>
                   </form>

               </div>
               <div class="clearfix"></div>
               <nav class="menu" >
                   <ul class="nav">
                       <li class="nav-item"><a>Home</a></li>
                       <li class="nav-item"><a>TVplay</a></li>
                       <li class="nav-item"><a>Top Movie</a></li>
                       <li class="nav-item"><a>News</a></li>
                       <li class="nav-item"><a>Pages</a></li>
                   </ul>
               </nav>
           </div>
           <ul class="col-lg-1">
               <span><a>Login</a></span>
               <span><a>Sign up</a></span>
           </ul>

       </div>

       </div>
       <section class="row">

       </section>

   </header>
   <main>


   </main>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>